TerrainHousing:
  Prefix: '&8[&aTerrain&eHousing&8]&r '
  OverrideProtections: false
  SignText:
    Available:
    - '&2--&a&lAvailable&2--'
    - ''
    - '&2Right Click'
    - '&2to claim'
    Occupied:
    - '&4--&c&lOccupied&4--'
    - '&c&1Occupied by'
    - '&l%player%'
    - '&bIdle: %timer%'
    Resetting:
    - '&c--&0&lResetting&c--'
    - '&4Session expired'
    - '&4Please return'
    - '&4later'
  Location: {}